<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        DB::table('accounts')->insert([
            [
                'id'=>1,
                'email'=>'binhdxth2004002@fpt.edu.vn',
                'password'=>'111111',
                'firstname'=>'Duong',
                'lastname'=>'Xuan Binh',
                'address'=>'Tay Mo, Nam Tu Liem, Ha Noi',
                'dob'=>'1995/11/10',
                'sex'=>'Male',
                'credit_number'=>'1111111111',
                'phone'=>'0947118116',
                'sky_miles'=>3663,
                'role'=>1
            ],
            [
                'id'=>2,
                'email'=>'datntth2002021@fpt.edu.vn',
                'password'=>'111111',
                'firstname'=>'Nguyen',
                'lastname'=>'Tien Dat',
                'address'=>'Van Phuc, Ha Dong, Ha Noi',
                'dob'=>'1996/5/13',
                'sex'=>'Male',
                'credit_number'=>'2222222222',
                'phone'=>'0852873838',
                'sky_miles'=>1221,
                'role'=>1
            ],
            [
                'id'=>3,
                'email'=>'xuanbinh1011@gmail.com',
                'password'=>'111111',
                'firstname'=>'Nguyen',
                'lastname'=>'Thai Son',
                'address'=>'Quang An, Tay Ho, Ha Noi',
                'dob'=>'1996/3/15',
                'sex'=>'Female',
                'credit_number'=>'3333333333',
                'phone'=>'0912164000',
                'sky_miles'=>1030,
                'role'=>1
            ],
            [
                'id'=>4,
                'email'=>'xubiii.95@gmail.com',
                'password'=>'111111',
                'firstname'=>'Ad',
                'lastname'=>'min',
                'address'=>'Tay Mo, Nam Tu Liem, Ha Noi',
                'dob'=>'1995/10/11',
                'sex'=>'Male',
                'credit_number'=>'4444444444',
                'phone'=>'0932555666',
                'sky_miles'=>0,
                'role'=>2
            ]
        ]);
        DB::table('airports')->insert([
            [
                'id'=>'HAN',
                'name'=>'Ha Noi',
            ],
            [
                'id'=>'SGN',
                'name'=>'TP Ho Chi Minh',
            ],
            [
                'id'=>'CXR',
                'name'=>'Nha Trang',
            ],
            [
                'id'=>'VDO',
                'name'=>'Van Don',
            ],
            [
                'id'=>'DAD',
                'name'=>'Da Nang',
            ]
        ]);
        DB::table('classes')->insert([
            [
                'id'=>1,
                'name'=>'Economy',
                'hand_baggage'=>'7kg',
                'checked_baggage'=>'20kg'
            ],
            [
                'id'=>2,
                'name'=>'Business',
                'hand_baggage'=>'10kg',
                'checked_baggage'=>'40kg'
            ]
        ]);
        DB::table('customers')->insert([
            [
                'id'=>10000101,
                'firstname'=>'Duong',
                'lastname'=>'Thuy Ngan',
                'dob'=>'1990/8/1',
                'account_id'=>1
            ],
            [
                'id'=>10000102,
                'firstname'=>'Nguyen',
                'lastname'=>'Thi Hang',
                'dob'=>'1968/9/9',
                'account_id'=>1
            ],
            [
                'id'=>10000103,
                'firstname'=>'Nguyen',
                'lastname'=>'Thuy Linh',
                'dob'=>'1991/9/9',
                'account_id'=>2
            ],
        ]);
        DB::table('customer_types')->insert([
            [
                'id'=>1,
                'name'=>'Children',
                'min_age'=>0,
                'max_age'=>10,
                'fare_diff'=>0.6
            ],
            [
                'id'=>2,
                'name'=>'Aldult',
                'min_age'=>11,
                'max_age'=>65,
                'fare_diff'=>1.0
            ],
            [
                'id'=>3,
                'name'=>'Senior citizen',
                'min_age'=>66,
                'max_age'=>200,
                'fare_diff'=>0.8
            ]
        ]);
        DB::table('flights')->insert([
            [
                'id'=>'HV111',
                'origin_airportid'=>'HAN',
                'arrival_airportid'=>'SGN',
                'departure_date'=>'2021/4/1 09:30',
                'arrival_date'=>'2021/4/1 11:20',
                'statusid'=>4,
                'planeid'=>2,
            ],
            [
                'id'=>'HV114',
                'origin_airportid'=>'HAN',
                'arrival_airportid'=>'SGN',
                'departure_date'=>'2021/4/7 6:30',
                'arrival_date'=>'2021/4/7 08:20',
                'statusid'=>1,
                'planeid'=>2,
            ],
            [
                'id'=>'HV115',
                'origin_airportid'=>'HAN',
                'arrival_airportid'=>'SGN',
                'departure_date'=>'2021/4/7 16:15',
                'arrival_date'=>'2021/4/7 18:05',
                'statusid'=>1,
                'planeid'=>2,
            ],
            [
                'id'=>'HV116',
                'origin_airportid'=>'HAN',
                'arrival_airportid'=>'SGN',
                'departure_date'=>'2021/4/8 12:00',
                'arrival_date'=>'2021/4/8 13:50',
                'statusid'=>1,
                'planeid'=>3,
            ],
            [
                'id'=>'HV117',
                'origin_airportid'=>'HAN',
                'arrival_airportid'=>'SGN',
                'departure_date'=>'2021/4/8 16:20',
                'arrival_date'=>'2021/4/8 18:10',
                'statusid'=>1,
                'planeid'=>2,
            ],
            [
                'id'=>'HV118',
                'origin_airportid'=>'HAN',
                'arrival_airportid'=>'SGN',
                'departure_date'=>'2021/4/9 08:15',
                'arrival_date'=>'2021/4/9 10:05',
                'statusid'=>1,
                'planeid'=>1,
            ],
            [
                'id'=>'HV119',
                'origin_airportid'=>'HAN',
                'arrival_airportid'=>'SGN',
                'departure_date'=>'2021/4/9 13:55',
                'arrival_date'=>'2021/4/9 16:45',
                'statusid'=>1,
                'planeid'=>1,
            ],
            [
                'id'=>'HV120',
                'origin_airportid'=>'HAN',
                'arrival_airportid'=>'SGN',
                'departure_date'=>'2021/4/10 9:00',
                'arrival_date'=>'2021/4/10 10:50',
                'statusid'=>1,
                'planeid'=>2,
            ],
            [
                'id'=>'HV121',
                'origin_airportid'=>'HAN',
                'arrival_airportid'=>'SGN',
                'departure_date'=>'2021/4/10 14:35',
                'arrival_date'=>'2021/4/10 16:25',
                'statusid'=>1,
                'planeid'=>2,
            ],

//            ------------------Route--------------------
            [
                'id'=>'HV112',
                'origin_airportid'=>'SGN',
                'arrival_airportid'=>'HAN',
                'departure_date'=>'2021/4/2 14:10',
                'arrival_date'=>'2021/4/2 16:00',
                'statusid'=>4,
                'planeid'=>1,
            ],
            [
                'id'=>'HV122',
                'origin_airportid'=>'SGN',
                'arrival_airportid'=>'HAN',
                'departure_date'=>'2021/4/7 10:20',
                'arrival_date'=>'2021/4/7 12:10',
                'statusid'=>1,
                'planeid'=>2,
            ],
            [
                'id'=>'HV123',
                'origin_airportid'=>'SGN',
                'arrival_airportid'=>'HAN',
                'departure_date'=>'2021/4/7 20:30',
                'arrival_date'=>'2021/4/7 22:30',
                'statusid'=>1,
                'planeid'=>2,
            ],
            [
                'id'=>'HV124',
                'origin_airportid'=>'SGN',
                'arrival_airportid'=>'HAN',
                'departure_date'=>'2021/4/8 16:00',
                'arrival_date'=>'2021/4/8 17:50',
                'statusid'=>1,
                'planeid'=>3,
            ],
            [
                'id'=>'HV125',
                'origin_airportid'=>'SGN',
                'arrival_airportid'=>'HAN',
                'departure_date'=>'2021/4/8 20:00',
                'arrival_date'=>'2021/4/8 21:50',
                'statusid'=>1,
                'planeid'=>2,
            ],
            [
                'id'=>'HV126',
                'origin_airportid'=>'SGN',
                'arrival_airportid'=>'HAN',
                'departure_date'=>'2021/4/9 11:30',
                'arrival_date'=>'2021/4/9 13:20',
                'statusid'=>1,
                'planeid'=>1,
            ],
            [
                'id'=>'HV127',
                'origin_airportid'=>'SGN',
                'arrival_airportid'=>'HAN',
                'departure_date'=>'2021/4/9 17:35',
                'arrival_date'=>'2021/4/9 19:25',
                'statusid'=>1,
                'planeid'=>1,
            ],
            [
                'id'=>'HV128',
                'origin_airportid'=>'SGN',
                'arrival_airportid'=>'HAN',
                'departure_date'=>'2021/4/10 06:00',
                'arrival_date'=>'2021/4/10 07:50',
                'statusid'=>1,
                'planeid'=>2,
            ],
            [
                'id'=>'HV129',
                'origin_airportid'=>'SGN',
                'arrival_airportid'=>'HAN',
                'departure_date'=>'2021/4/10 11:50',
                'arrival_date'=>'2021/4/10 13:40',
                'statusid'=>1,
                'planeid'=>2,
            ],

            //            ------------------Route--------------------
            [
                'id'=>'HV113',
                'origin_airportid'=>'VDO',
                'arrival_airportid'=>'CXR',
                'departure_date'=>'2021/4/2 20:20',
                'arrival_date'=>'2021/4/2 22:00',
                'statusid'=>4,
                'planeid'=>1,
            ],
            [
                'id'=>'HV130',
                'origin_airportid'=>'VDO',
                'arrival_airportid'=>'CXR',
                'departure_date'=>'2021/4/7 7:25',
                'arrival_date'=>'2021/4/7 9:05',
                'statusid'=>1,
                'planeid'=>1,
            ],
            [
                'id'=>'HV131',
                'origin_airportid'=>'VDO',
                'arrival_airportid'=>'CXR',
                'departure_date'=>'2021/4/7 10:10',
                'arrival_date'=>'2021/4/7 11:50',
                'statusid'=>1,
                'planeid'=>2,
            ],
            [
                'id'=>'HV132',
                'origin_airportid'=>'VDO',
                'arrival_airportid'=>'CXR',
                'departure_date'=>'2021/4/8 16:15',
                'arrival_date'=>'2021/4/8 17:55',
                'statusid'=>1,
                'planeid'=>3,
            ],
            [
                'id'=>'HV133',
                'origin_airportid'=>'VDO',
                'arrival_airportid'=>'CXR',
                'departure_date'=>'2021/4/8 20:50',
                'arrival_date'=>'2021/4/8 21:30',
                'statusid'=>1,
                'planeid'=>2,
            ],
            [
                'id'=>'HV134',
                'origin_airportid'=>'VDO',
                'arrival_airportid'=>'CXR',
                'departure_date'=>'2021/4/9 8:00',
                'arrival_date'=>'2021/4/9 9:40',
                'statusid'=>1,
                'planeid'=>1,
            ],
            [
                'id'=>'HV135',
                'origin_airportid'=>'VDO',
                'arrival_airportid'=>'CXR',
                'departure_date'=>'2021/4/9 13:00',
                'arrival_date'=>'2021/4/9 14:40',
                'statusid'=>1,
                'planeid'=>2,
            ],
            [
                'id'=>'HV136',
                'origin_airportid'=>'VDO',
                'arrival_airportid'=>'CXR',
                'departure_date'=>'2021/4/10 15:15',
                'arrival_date'=>'2021/4/10 16:55',
                'statusid'=>1,
                'planeid'=>1,
            ],
            [
                'id'=>'HV137',
                'origin_airportid'=>'VDO',
                'arrival_airportid'=>'CXR',
                'departure_date'=>'2021/4/10 18:05',
                'arrival_date'=>'2021/4/10 19:45',
                'statusid'=>1,
                'planeid'=>3,
            ],
            //            ------------------Route--------------------
            [
                'id'=>'HV138',
                'origin_airportid'=>'CXR',
                'arrival_airportid'=>'SGN',
                'departure_date'=>'2021/4/7 10:00',
                'arrival_date'=>'2021/4/7 11:00',
                'statusid'=>1,
                'planeid'=>1,
            ],
            [
                'id'=>'HV139',
                'origin_airportid'=>'CXR',
                'arrival_airportid'=>'SGN',
                'departure_date'=>'2021/4/7 13:00',
                'arrival_date'=>'2021/4/7 14:00',
                'statusid'=>1,
                'planeid'=>2,
            ],
            [
                'id'=>'HV140',
                'origin_airportid'=>'CXR',
                'arrival_airportid'=>'SGN',
                'departure_date'=>'2021/4/8 11:45',
                'arrival_date'=>'2021/4/8 12:45',
                'statusid'=>1,
                'planeid'=>1,
            ],
            [
                'id'=>'HV141',
                'origin_airportid'=>'CXR',
                'arrival_airportid'=>'SGN',
                'departure_date'=>'2021/4/8 19:30',
                'arrival_date'=>'2021/4/8 20:30',
                'statusid'=>1,
                'planeid'=>3,
            ],
            [
                'id'=>'HV142',
                'origin_airportid'=>'CXR',
                'arrival_airportid'=>'SGN',
                'departure_date'=>'2021/4/9 5:15',
                'arrival_date'=>'2021/4/9 6:15',
                'statusid'=>1,
                'planeid'=>3,
            ],
            [
                'id'=>'HV143',
                'origin_airportid'=>'CXR',
                'arrival_airportid'=>'SGN',
                'departure_date'=>'2021/4/9 10:15',
                'arrival_date'=>'2021/4/9 11:15',
                'statusid'=>1,
                'planeid'=>2,
            ],
            [
                'id'=>'HV144',
                'origin_airportid'=>'CXR',
                'arrival_airportid'=>'SGN',
                'departure_date'=>'2021/4/10 9:25',
                'arrival_date'=>'2021/4/10 10:25',
                'statusid'=>1,
                'planeid'=>1,
            ],
            [
                'id'=>'HV145',
                'origin_airportid'=>'CXR',
                'arrival_airportid'=>'SGN',
                'departure_date'=>'2021/4/10 16:35',
                'arrival_date'=>'2021/4/10 17:35',
                'statusid'=>1,
                'planeid'=>2,
            ],

            //            ------------------Route--------------------
            [
                'id'=>'HV146',
                'origin_airportid'=>'SGN',
                'arrival_airportid'=>'CXR',
                'departure_date'=>'2021/4/7 15:00',
                'arrival_date'=>'2021/4/7 16:00',
                'statusid'=>1,
                'planeid'=>3,
            ],
            [
                'id'=>'HV147',
                'origin_airportid'=>'SGN',
                'arrival_airportid'=>'CXR',
                'departure_date'=>'2021/4/7 08:15',
                'arrival_date'=>'2021/4/7 09:15',
                'statusid'=>1,
                'planeid'=>3,
            ],
            [
                'id'=>'HV148',
                'origin_airportid'=>'SGN',
                'arrival_airportid'=>'CXR',
                'departure_date'=>'2021/4/8 10:00',
                'arrival_date'=>'2021/4/8 11:00',
                'statusid'=>1,
                'planeid'=>2,
            ],
            [
                'id'=>'HV149',
                'origin_airportid'=>'SGN',
                'arrival_airportid'=>'CXR',
                'departure_date'=>'2021/4/8 21:00',
                'arrival_date'=>'2021/4/8 22:00',
                'statusid'=>1,
                'planeid'=>3,
            ],
            [
                'id'=>'HV150',
                'origin_airportid'=>'SGN',
                'arrival_airportid'=>'CXR',
                'departure_date'=>'2021/4/9 07:10',
                'arrival_date'=>'2021/4/9 08:10',
                'statusid'=>1,
                'planeid'=>1,
            ],
            [
                'id'=>'HV151',
                'origin_airportid'=>'SGN',
                'arrival_airportid'=>'CXR',
                'departure_date'=>'2021/4/9 12:15',
                'arrival_date'=>'2021/4/9 13:15',
                'statusid'=>1,
                'planeid'=>2,
            ],
            [
                'id'=>'HV152',
                'origin_airportid'=>'SGN',
                'arrival_airportid'=>'CXR',
                'departure_date'=>'2021/4/10 9:55',
                'arrival_date'=>'2021/4/10 10:55',
                'statusid'=>1,
                'planeid'=>3,
            ],
            [
                'id'=>'HV153',
                'origin_airportid'=>'SGN',
                'arrival_airportid'=>'CXR',
                'departure_date'=>'2021/4/10 15:15',
                'arrival_date'=>'2021/4/10 16:15',
                'statusid'=>1,
                'planeid'=>2,
            ],

            //            ------------------Route--------------------
            [
                'id'=>'HV154',
                'origin_airportid'=>'CXR',
                'arrival_airportid'=>'VDO',
                'departure_date'=>'2021/4/7 6:40',
                'arrival_date'=>'2021/4/7 8:20',
                'statusid'=>1,
                'planeid'=>1,
            ],
            [
                'id'=>'HV155',
                'origin_airportid'=>'CXR',
                'arrival_airportid'=>'VDO',
                'departure_date'=>'2021/4/7 10:00',
                'arrival_date'=>'2021/4/7 11:40',
                'statusid'=>1,
                'planeid'=>2,
            ],
            [
                'id'=>'HV156',
                'origin_airportid'=>'CXR',
                'arrival_airportid'=>'VDO',
                'departure_date'=>'2021/4/8 15:10',
                'arrival_date'=>'2021/4/8 16:50',
                'statusid'=>1,
                'planeid'=>3,
            ],
            [
                'id'=>'HV157',
                'origin_airportid'=>'CXR',
                'arrival_airportid'=>'VDO',
                'departure_date'=>'2021/4/8 21:20',
                'arrival_date'=>'2021/4/8 23:00',
                'statusid'=>1,
                'planeid'=>3,
            ],
            [
                'id'=>'HV158',
                'origin_airportid'=>'CXR',
                'arrival_airportid'=>'VDO',
                'departure_date'=>'2021/4/9 10:00',
                'arrival_date'=>'2021/4/9 11:40',
                'statusid'=>1,
                'planeid'=>3,
            ],
            [
                'id'=>'HV159',
                'origin_airportid'=>'CXR',
                'arrival_airportid'=>'VDO',
                'departure_date'=>'2021/4/9 14:55',
                'arrival_date'=>'2021/4/9 15:35',
                'statusid'=>1,
                'planeid'=>2,
            ],
            [
                'id'=>'HV160',
                'origin_airportid'=>'CXR',
                'arrival_airportid'=>'VDO',
                'departure_date'=>'2021/4/10 9:15',
                'arrival_date'=>'2021/4/10 10:55',
                'statusid'=>1,
                'planeid'=>3,
            ],
            [
                'id'=>'HV161',
                'origin_airportid'=>'CXR',
                'arrival_airportid'=>'VDO',
                'departure_date'=>'2021/4/10 17:35',
                'arrival_date'=>'2021/4/10 19:15',
                'statusid'=>1,
                'planeid'=>1,
            ],
            //            ------------------Route--------------------


        ]);
        DB::table('flight_statuses')->insert([
            [
                'id'=>1,
                'name'=>'As scheduled'
            ],
            [
                'id'=>2,
                'name'=>'Delayed'
            ],
            [
                'id'=>3,
                'name'=>'Cancelled'
            ],
            [
                'id'=>4,
                'name'=>'Landed'
            ]
        ]);
        DB::table('orders')->insert([
            [
                'id'=>'SO-AKEB',
                'account_id'=>1,
                'order_status'=>1,
                'total_price'=>'151.5',
                'total_skymiles'=>3663,
            ],
            [
                'id'=>'SO-HTBN',
                'account_id'=>2,
                'order_status'=>1,
                'total_price'=>'90',
                'total_skymiles'=>2442,
            ],
            [
                'id'=>'SO-MLTK',
                'account_id'=>3,
                'order_status'=>1,
                'total_price'=>52,
                'total_skymiles'=>1030,
            ],
        ]);
        DB::table('planes')->insert([
            [
                'id'=>1,
                'name'=>'MB111',
                'plane_type'=>1
            ],
            [
                'id'=>2,
                'name'=>'MB112',
                'plane_type'=>2
            ],
            [
                'id'=>3,
                'name'=>'MB113',
                'plane_type'=>2
            ]
        ]);
        DB::table('plane_types')->insert([
            [
                'id'=>1,
                'name'=>'Airbus 320_200',
                'total_seats'=>142
            ],
            [
                'id'=>2,
                'name'=>'Boeing 787-800',
                'total_seats'=>235,
            ]
        ]);
        DB::table('roles')->insert([
            [
                'id'=>1,
                'name'=>'passenger'
            ],
            [
                'id'=>2,
                'name'=>'admin'
            ]
        ]);
        DB::table('route_directs')->insert([
            [
                'id'=>'1',
                'origin_airportid'=>'HAN',
                'transit_airportid'=>'',
                'arrival_airportid'=>'SGN',
                'skymile'=>'1221',
                'duration'=>'1:50'
            ],
            [
                'id'=>'2',
                'origin_airportid'=>'SGN',
                'transit_airportid'=>'',
                'arrival_airportid'=>'HAN',
                'skymile'=>'1221',
                'duration'=>'1:50'
            ],
            [
                'id'=>'3',
                'origin_airportid'=>'HAN',
                'transit_airportid'=>'',
                'arrival_airportid'=>'CXR',
                'skymile'=>'860',
                'duration'=>'1:20'
            ],
            [
                'id'=>'4',
                'origin_airportid'=>'CXR',
                'transit_airportid'=>'',
                'arrival_airportid'=>'HAN',
                'skymile'=>'860',
                'duration'=>'1:20'
            ],
            [
                'id'=>'5',
                'origin_airportid'=>'VDO',
                'transit_airportid'=>'',
                'arrival_airportid'=>'DAD',
                'skymile'=>'920',
                'duration'=>'1:30'
            ],
            [
                'id'=>'6',
                'origin_airportid'=>'DAD',
                'transit_airportid'=>'',
                'arrival_airportid'=>'VDO',
                'skymile'=>'920',
                'duration'=>'1:30'
            ],
            [
                'id'=>'7',
                'origin_airportid'=>'DAD',
                'transit_airportid'=>'',
                'arrival_airportid'=>'SGN',
                'skymile'=>'670',
                'duration'=>'1:05'
            ],
            [
                'id'=>'8',
                'origin_airportid'=>'SGN',
                'transit_airportid'=>'',
                'arrival_airportid'=>'DAD',
                'skymile'=>'670',
                'duration'=>'1:05'
            ],
            [
                'id'=>'9',
                'origin_airportid'=>'VDO',
                'transit_airportid'=>'',
                'arrival_airportid'=>'CXR',
                'skymile'=>'1030',
                'duration'=>'1:40'
            ],
            [
                'id'=>'10',
                'origin_airportid'=>'CXR',
                'transit_airportid'=>'',
                'arrival_airportid'=>'VDO',
                'skymile'=>'1030',
                'duration'=>'1:40'
            ],
            [
                'id'=>'11',
                'origin_airportid'=>'CXR',
                'transit_airportid'=>'',
                'arrival_airportid'=>'SGN',
                'skymile'=>'480',
                'duration'=>'1:00'
            ],
            [
                'id'=>'12',
                'origin_airportid'=>'SGN',
                'transit_airportid'=>'',
                'arrival_airportid'=>'CXR',
                'skymile'=>'480',
                'duration'=>'1:00'
            ],
            [
                'id'=>'13',
                'origin_airportid'=>'VDO',
                'transit_airportid'=>'DAD',
                'arrival_airportid'=>'SGN',
                'skymile'=>'1590',
                'duration'=>'2:45'
            ],
            [
                'id'=>'14',
                'origin_airportid'=>'VOD',
                'transit_airportid'=>'CXR',
                'arrival_airportid'=>'SGN',
                'skymile'=>'1510',
                'duration'=>'2:55'
            ],
            [
                'id'=>'15',
                'origin_airportid'=>'SGN',
                'transit_airportid'=>'DAD',
                'arrival_airportid'=>'VDO',
                'skymile'=>'1590',
                'duration'=>'2:45'
            ],
            [
                'id'=>'16',
                'origin_airportid'=>'SGN',
                'transit_airportid'=>'CXR',
                'arrival_airportid'=>'VDO',
                'skymile'=>'1510',
                'duration'=>'2:55'
            ],
        ]);
        DB::table('seats')->insert([
            //320
            [ 'seat_location'=>'1A', 'class_id'=>2, 'plane_type'=>1 ],
            [ 'seat_location'=>'1B', 'class_id'=>2, 'plane_type'=>1 ],
            [ 'seat_location'=>'1C', 'class_id'=>2, 'plane_type'=>1 ],
            [ 'seat_location'=>'1D', 'class_id'=>2, 'plane_type'=>1 ],
            [ 'seat_location'=>'2A', 'class_id'=>2, 'plane_type'=>1 ],
            [ 'seat_location'=>'2B', 'class_id'=>2, 'plane_type'=>1 ],
            [ 'seat_location'=>'2C', 'class_id'=>2, 'plane_type'=>1 ],
            [ 'seat_location'=>'2D', 'class_id'=>2, 'plane_type'=>1 ],
            [ 'seat_location'=>'3A', 'class_id'=>2, 'plane_type'=>1 ],
            [ 'seat_location'=>'3B', 'class_id'=>2, 'plane_type'=>1 ],
            [ 'seat_location'=>'3C', 'class_id'=>2, 'plane_type'=>1 ],
            [ 'seat_location'=>'3D', 'class_id'=>2, 'plane_type'=>1 ],
            [ 'seat_location'=>'4A', 'class_id'=>2, 'plane_type'=>1 ],
            [ 'seat_location'=>'4B', 'class_id'=>2, 'plane_type'=>1 ],
            [ 'seat_location'=>'4C', 'class_id'=>2, 'plane_type'=>1 ],
            [ 'seat_location'=>'4D', 'class_id'=>2, 'plane_type'=>1 ],
            [ 'seat_location'=>'5A', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'5B', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'5C', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'5D', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'5E', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'5G', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'6A', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'6B', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'6C', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'6D', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'6E', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'6G', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'7A', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'7B', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'7C', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'7D', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'7E', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'7G', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'8A', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'8B', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'8C', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'8D', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'8E', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'8G', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'9A', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'9B', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'9C', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'9D', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'9E', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'9G', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'10A', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'10B', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'10C', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'10D', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'10E', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'10G', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'11A', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'11B', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'11C', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'11D', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'11E', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'11G', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'12A', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'12B', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'12C', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'12D', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'12E', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'12G', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'13A', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'13B', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'13C', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'13D', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'13E', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'13G', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'14A', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'14B', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'14C', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'14D', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'14E', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'14G', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'15A', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'15B', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'15C', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'15D', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'15E', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'15G', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'16A', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'16B', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'16C', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'16D', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'16E', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'16G', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'17A', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'17B', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'17C', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'17D', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'17E', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'17G', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'18A', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'18B', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'18C', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'18D', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'18E', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'18G', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'19A', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'19B', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'19C', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'19D', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'19E', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'19G', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'20A', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'20B', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'20C', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'20D', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'20E', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'20G', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'21A', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'21B', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'21C', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'21D', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'21E', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'21G', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'22A', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'22B', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'22C', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'22D', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'22E', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'22G', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'23A', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'23B', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'23C', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'23D', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'23E', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'23G', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'24A', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'24B', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'24C', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'24D', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'24E', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'24G', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'25A', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'25B', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'25C', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'25D', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'25E', 'class_id'=>1, 'plane_type'=>1 ],
            [ 'seat_location'=>'25G', 'class_id'=>1, 'plane_type'=>1 ],
            //787-1
            [ 'seat_location'=>'1A', 'class_id'=>2, 'plane_type'=>2 ],
            [ 'seat_location'=>'1B', 'class_id'=>2, 'plane_type'=>2 ],
            [ 'seat_location'=>'1C', 'class_id'=>2, 'plane_type'=>2 ],
            [ 'seat_location'=>'1D', 'class_id'=>2, 'plane_type'=>2 ],
            [ 'seat_location'=>'2A', 'class_id'=>2, 'plane_type'=>2 ],
            [ 'seat_location'=>'2B', 'class_id'=>2, 'plane_type'=>2 ],
            [ 'seat_location'=>'2C', 'class_id'=>2, 'plane_type'=>2 ],
            [ 'seat_location'=>'2D', 'class_id'=>2, 'plane_type'=>2 ],
            [ 'seat_location'=>'3A', 'class_id'=>2, 'plane_type'=>2 ],
            [ 'seat_location'=>'3B', 'class_id'=>2, 'plane_type'=>2 ],
            [ 'seat_location'=>'3C', 'class_id'=>2, 'plane_type'=>2 ],
            [ 'seat_location'=>'3D', 'class_id'=>2, 'plane_type'=>2 ],
            [ 'seat_location'=>'4A', 'class_id'=>2, 'plane_type'=>2 ],
            [ 'seat_location'=>'4B', 'class_id'=>2, 'plane_type'=>2 ],
            [ 'seat_location'=>'4C', 'class_id'=>2, 'plane_type'=>2 ],
            [ 'seat_location'=>'4D', 'class_id'=>2, 'plane_type'=>2 ],
            [ 'seat_location'=>'5A', 'class_id'=>2, 'plane_type'=>2 ],
            [ 'seat_location'=>'5B', 'class_id'=>2, 'plane_type'=>2 ],
            [ 'seat_location'=>'5C', 'class_id'=>2, 'plane_type'=>2 ],
            [ 'seat_location'=>'5D', 'class_id'=>2, 'plane_type'=>2 ],
            [ 'seat_location'=>'6A', 'class_id'=>2, 'plane_type'=>2 ],
            [ 'seat_location'=>'6B', 'class_id'=>2, 'plane_type'=>2 ],
            [ 'seat_location'=>'6C', 'class_id'=>2, 'plane_type'=>2 ],
            [ 'seat_location'=>'6D', 'class_id'=>2, 'plane_type'=>2 ],
            [ 'seat_location'=>'7A', 'class_id'=>2, 'plane_type'=>2 ],
            [ 'seat_location'=>'7B', 'class_id'=>2, 'plane_type'=>2 ],
            [ 'seat_location'=>'7C', 'class_id'=>2, 'plane_type'=>2 ],
            [ 'seat_location'=>'7D', 'class_id'=>2, 'plane_type'=>2 ],
            [ 'seat_location'=>'8A', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'8B', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'8C', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'8D', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'8E', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'8F', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'8G', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'8H', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'8K', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'9A', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'9B', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'9C', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'9D', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'9E', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'9F', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'9G', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'9H', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'9K', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'10A', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'10B', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'10C', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'10D', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'10E', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'10F', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'10G', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'10H', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'10K', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'11A', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'11B', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'11C', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'11D', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'11E', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'11F', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'11G', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'11H', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'11K', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'12A', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'12B', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'12C', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'12D', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'12E', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'12F', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'12G', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'12H', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'12K', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'13A', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'13B', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'13C', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'13D', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'13E', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'13F', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'13G', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'13H', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'13K', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'14A', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'14B', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'14C', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'14D', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'14E', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'14F', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'14G', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'14H', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'14K', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'15A', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'15B', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'15C', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'15D', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'15E', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'15F', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'15G', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'15H', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'15K', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'16A', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'16B', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'16C', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'16D', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'16E', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'16F', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'16G', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'16H', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'16K', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'17A', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'17B', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'17C', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'17D', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'17E', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'17F', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'17G', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'17H', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'17K', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'18A', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'18B', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'18C', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'18D', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'18E', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'18F', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'18G', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'18H', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'18K', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'19A', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'19B', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'19C', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'19D', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'19E', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'19F', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'19G', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'19H', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'19K', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'20A', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'20B', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'20C', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'20D', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'20E', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'20F', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'20G', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'20H', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'20K', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'21A', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'21B', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'21C', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'21D', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'21E', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'21F', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'21G', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'21H', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'21K', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'22A', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'22B', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'22C', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'22D', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'22E', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'22F', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'22G', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'22H', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'22K', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'23A', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'23B', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'23C', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'23D', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'23E', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'23F', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'23G', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'23H', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'23K', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'24A', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'24B', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'24C', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'24D', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'24E', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'24F', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'24G', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'24H', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'24K', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'25A', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'25B', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'25C', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'25D', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'25E', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'25F', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'25G', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'25H', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'25K', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'26A', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'26B', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'26C', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'26D', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'26E', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'26F', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'26G', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'26H', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'26K', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'27A', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'27B', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'27C', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'27D', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'27E', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'27F', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'27G', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'27H', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'27K', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'28A', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'28B', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'28C', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'28D', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'28E', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'28F', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'28G', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'28H', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'28K', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'29A', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'29B', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'29C', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'29D', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'29E', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'29F', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'29G', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'29H', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'29K', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'30A', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'30B', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'30C', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'30D', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'30E', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'30F', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'30G', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'30H', 'class_id'=>1, 'plane_type'=>2 ],
            [ 'seat_location'=>'30K', 'class_id'=>1, 'plane_type'=>2 ],

        ]);
        DB::table('ticket_details')->insert([
            [
                'flight_id'=>'HV111',
                'seat_location'=>'10A',
                'order_id'=>'SO-AKEB',
                'passenger_id'=>1,
                'price'=>50.5
            ],
            [
                'flight_id'=>'HV111',
                'seat_location'=>'10B',
                'order_id'=>'SO-AKEB',
                'passenger_id'=>'10000101',
                'price'=>50.5
            ],
            [
                'flight_id'=>'HV111',
                'seat_location'=>'10C',
                'order_id'=>'SO-AKEB',
                'passenger_id'=>'10000102',
                'price'=>50.5
            ],
            [
                'flight_id'=>'HV112',
                'seat_location'=>'24C',
                'order_id'=>'SO-HTBN',
                'passenger_id'=>2,
                'price'=>45
            ],
            [
                'flight_id'=>'HV112',
                'seat_location'=>'15A',
                'order_id'=>'SO-HTBN',
                'passenger_id'=>10000103,
                'price'=>45
            ],
            [
                'flight_id'=>'HV113',
                'seat_location'=>'1A',
                'order_id'=>'SO-MLTK',
                'passenger_id'=>3,
                'price'=>52
            ],

        ]);
        DB::table('ticket_prices')->insert([
            [
                'flight_id'=>'HV111',
                'class_id'=>1,
                'price'=>50.5,
            ],
            [
                'flight_id'=>'HV111',
                'class_id'=>2,
                'price'=>71.3,
            ],
            [
                'flight_id'=>'HV112',
                'class_id'=>1,
                'price'=>45,
            ],
            [
                'flight_id'=>'HV112',
                'class_id'=>2,
                'price'=>68.9,
            ],
            [
                'flight_id'=>'HV113',
                'class_id'=>1,
                'price'=>39,
            ],
            [
                'flight_id'=>'HV113',
                'class_id'=>2,
                'price'=>52,
            ],
            ['flight_id'=>'HV114', 'class_id'=>1, 'price'=>80 ],
            ['flight_id'=>'HV114', 'class_id'=>2, 'price'=>104 ],
            ['flight_id'=>'HV115', 'class_id'=>1, 'price'=>82 ],
            ['flight_id'=>'HV115', 'class_id'=>2, 'price'=>97 ],
            ['flight_id'=>'HV116', 'class_id'=>1, 'price'=>34 ],
            ['flight_id'=>'HV116', 'class_id'=>2, 'price'=>60 ],
            ['flight_id'=>'HV117', 'class_id'=>1, 'price'=>98 ],
            ['flight_id'=>'HV117', 'class_id'=>2, 'price'=>117 ],
            ['flight_id'=>'HV118', 'class_id'=>1, 'price'=>76 ],
            ['flight_id'=>'HV118', 'class_id'=>2, 'price'=>87 ],
            ['flight_id'=>'HV119', 'class_id'=>1, 'price'=>32 ],
            ['flight_id'=>'HV119', 'class_id'=>2, 'price'=>58 ],
            ['flight_id'=>'HV120', 'class_id'=>1, 'price'=>47 ],
            ['flight_id'=>'HV120', 'class_id'=>2, 'price'=>71 ],
            ['flight_id'=>'HV121', 'class_id'=>1, 'price'=>93 ],
            ['flight_id'=>'HV121', 'class_id'=>2, 'price'=>110 ],
            ['flight_id'=>'HV122', 'class_id'=>1, 'price'=>68 ],
            ['flight_id'=>'HV122', 'class_id'=>2, 'price'=>84 ],
            ['flight_id'=>'HV123', 'class_id'=>1, 'price'=>93 ],
            ['flight_id'=>'HV123', 'class_id'=>2, 'price'=>115 ],
            ['flight_id'=>'HV124', 'class_id'=>1, 'price'=>74 ],
            ['flight_id'=>'HV124', 'class_id'=>2, 'price'=>91 ],
            ['flight_id'=>'HV125', 'class_id'=>1, 'price'=>72 ],
            ['flight_id'=>'HV125', 'class_id'=>2, 'price'=>82 ],
            ['flight_id'=>'HV126', 'class_id'=>1, 'price'=>44 ],
            ['flight_id'=>'HV126', 'class_id'=>2, 'price'=>57 ],
            ['flight_id'=>'HV127', 'class_id'=>1, 'price'=>69 ],
            ['flight_id'=>'HV127', 'class_id'=>2, 'price'=>88 ],
            ['flight_id'=>'HV128', 'class_id'=>1, 'price'=>32 ],
            ['flight_id'=>'HV128', 'class_id'=>2, 'price'=>59 ],
            ['flight_id'=>'HV129', 'class_id'=>1, 'price'=>50 ],
            ['flight_id'=>'HV129', 'class_id'=>2, 'price'=>67 ],
            ['flight_id'=>'HV130', 'class_id'=>1, 'price'=>38 ],
            ['flight_id'=>'HV130', 'class_id'=>2, 'price'=>57 ],
            ['flight_id'=>'HV131', 'class_id'=>1, 'price'=>52 ],
            ['flight_id'=>'HV131', 'class_id'=>2, 'price'=>65 ],
            ['flight_id'=>'HV132', 'class_id'=>1, 'price'=>75 ],
            ['flight_id'=>'HV132', 'class_id'=>2, 'price'=>91 ],
            ['flight_id'=>'HV133', 'class_id'=>1, 'price'=>99 ],
            ['flight_id'=>'HV133', 'class_id'=>2, 'price'=>111 ],
            ['flight_id'=>'HV134', 'class_id'=>1, 'price'=>84 ],
            ['flight_id'=>'HV134', 'class_id'=>2, 'price'=>105 ],
            ['flight_id'=>'HV135', 'class_id'=>1, 'price'=>71 ],
            ['flight_id'=>'HV135', 'class_id'=>2, 'price'=>96 ],
            ['flight_id'=>'HV136', 'class_id'=>1, 'price'=>76 ],
            ['flight_id'=>'HV136', 'class_id'=>2, 'price'=>103 ],
            ['flight_id'=>'HV137', 'class_id'=>1, 'price'=>75 ],
            ['flight_id'=>'HV137', 'class_id'=>2, 'price'=>101 ],
            ['flight_id'=>'HV138', 'class_id'=>1, 'price'=>60 ],
            ['flight_id'=>'HV138', 'class_id'=>2, 'price'=>79 ],
            ['flight_id'=>'HV139', 'class_id'=>1, 'price'=>55 ],
            ['flight_id'=>'HV139', 'class_id'=>2, 'price'=>76 ],
            ['flight_id'=>'HV140', 'class_id'=>1, 'price'=>39 ],
            ['flight_id'=>'HV140', 'class_id'=>2, 'price'=>62 ],
            ['flight_id'=>'HV141', 'class_id'=>1, 'price'=>36 ],
            ['flight_id'=>'HV141', 'class_id'=>2, 'price'=>47 ],
            ['flight_id'=>'HV142', 'class_id'=>1, 'price'=>83 ],
            ['flight_id'=>'HV142', 'class_id'=>2, 'price'=>98 ],
            ['flight_id'=>'HV143', 'class_id'=>1, 'price'=>34 ],
            ['flight_id'=>'HV143', 'class_id'=>2, 'price'=>54 ],
            ['flight_id'=>'HV144', 'class_id'=>1, 'price'=>84 ],
            ['flight_id'=>'HV144', 'class_id'=>2, 'price'=>104 ],
            ['flight_id'=>'HV145', 'class_id'=>1, 'price'=>77 ],
            ['flight_id'=>'HV145', 'class_id'=>2, 'price'=>97 ],
            ['flight_id'=>'HV146', 'class_id'=>1, 'price'=>61 ],
            ['flight_id'=>'HV146', 'class_id'=>2, 'price'=>85 ],
            ['flight_id'=>'HV147', 'class_id'=>1, 'price'=>50 ],
            ['flight_id'=>'HV147', 'class_id'=>2, 'price'=>78 ],
            ['flight_id'=>'HV148', 'class_id'=>1, 'price'=>80 ],
            ['flight_id'=>'HV148', 'class_id'=>2, 'price'=>91 ],
            ['flight_id'=>'HV149', 'class_id'=>1, 'price'=>24 ],
            ['flight_id'=>'HV149', 'class_id'=>2, 'price'=>49 ],
            ['flight_id'=>'HV150', 'class_id'=>1, 'price'=>74 ],
            ['flight_id'=>'HV150', 'class_id'=>2, 'price'=>87 ],
            ['flight_id'=>'HV151', 'class_id'=>1, 'price'=>92 ],
            ['flight_id'=>'HV151', 'class_id'=>2, 'price'=>116 ],
            ['flight_id'=>'HV152', 'class_id'=>1, 'price'=>68 ],
            ['flight_id'=>'HV152', 'class_id'=>2, 'price'=>78 ],
            ['flight_id'=>'HV153', 'class_id'=>1, 'price'=>76 ],
            ['flight_id'=>'HV153', 'class_id'=>2, 'price'=>101 ],
            ['flight_id'=>'HV154', 'class_id'=>1, 'price'=>43 ],
            ['flight_id'=>'HV154', 'class_id'=>2, 'price'=>71 ],
            ['flight_id'=>'HV155', 'class_id'=>1, 'price'=>23 ],
            ['flight_id'=>'HV155', 'class_id'=>2, 'price'=>40 ],
            ['flight_id'=>'HV156', 'class_id'=>1, 'price'=>26 ],
            ['flight_id'=>'HV156', 'class_id'=>2, 'price'=>38 ],
            ['flight_id'=>'HV157', 'class_id'=>1, 'price'=>27 ],
            ['flight_id'=>'HV157', 'class_id'=>2, 'price'=>47 ],
            ['flight_id'=>'HV158', 'class_id'=>1, 'price'=>90 ],
            ['flight_id'=>'HV158', 'class_id'=>2, 'price'=>101 ],
            ['flight_id'=>'HV159', 'class_id'=>1, 'price'=>84 ],
            ['flight_id'=>'HV159', 'class_id'=>2, 'price'=>110 ],
            ['flight_id'=>'HV160', 'class_id'=>1, 'price'=>65 ],
            ['flight_id'=>'HV160', 'class_id'=>2, 'price'=>76 ],
            ['flight_id'=>'HV161', 'class_id'=>1, 'price'=>95 ],
            ['flight_id'=>'HV161', 'class_id'=>2, 'price'=>108 ],
        ]);
        DB::table('order_statuses')->insert([
            [
                'id'=>1,
                'name'=>'Buyed',
            ],[
                'id'=>2,
                'name'=>'Blocked',
            ],
            [
                'id'=>3,
                'name'=>'Cancelled'
            ]
        ]);
    }
}
