<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TicketPriceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('ticket_prices')->insert([
            [
                'flight_id'=>'HV111',
                'class_id'=>1,
                'price'=>50.5,
            ],
            [
                'flight_id'=>'HV111',
                'class_id'=>2,
                'price'=>71.3,
            ],
            [
                'flight_id'=>'HV112',
                'class_id'=>1,
                'price'=>45,
            ],
            [
                'flight_id'=>'HV112',
                'class_id'=>2,
                'price'=>68.9,
            ],
            [
                'flight_id'=>'HV113',
                'class_id'=>1,
                'price'=>39,
            ],
            [
            'flight_id'=>'HV113',
                'class_id'=>2,
                'price'=>52,
            ],
            ['flight_id'=>'HV.114', 'class_id'=>1, 'price'=>80 ],
            ['flight_id'=>'HV.114', 'class_id'=>2, 'price'=>104 ],
            ['flight_id'=>'HV.115', 'class_id'=>1, 'price'=>82 ],
            ['flight_id'=>'HV.115', 'class_id'=>2, 'price'=>97 ],
            ['flight_id'=>'HV.116', 'class_id'=>1, 'price'=>34 ],
            ['flight_id'=>'HV.116', 'class_id'=>2, 'price'=>60 ],
            ['flight_id'=>'HV.117', 'class_id'=>1, 'price'=>98 ],
            ['flight_id'=>'HV.117', 'class_id'=>2, 'price'=>117 ],
            ['flight_id'=>'HV.118', 'class_id'=>1, 'price'=>76 ],
            ['flight_id'=>'HV.118', 'class_id'=>2, 'price'=>87 ],
            ['flight_id'=>'HV.119', 'class_id'=>1, 'price'=>32 ],
            ['flight_id'=>'HV.119', 'class_id'=>2, 'price'=>58 ],
            ['flight_id'=>'HV.120', 'class_id'=>1, 'price'=>47 ],
            ['flight_id'=>'HV.120', 'class_id'=>2, 'price'=>71 ],
            ['flight_id'=>'HV.121', 'class_id'=>1, 'price'=>93 ],
            ['flight_id'=>'HV.121', 'class_id'=>2, 'price'=>110 ],
            ['flight_id'=>'HV.122', 'class_id'=>1, 'price'=>68 ],
            ['flight_id'=>'HV.122', 'class_id'=>2, 'price'=>84 ],
            ['flight_id'=>'HV.123', 'class_id'=>1, 'price'=>93 ],
            ['flight_id'=>'HV.123', 'class_id'=>2, 'price'=>115 ],
            ['flight_id'=>'HV.124', 'class_id'=>1, 'price'=>74 ],
            ['flight_id'=>'HV.124', 'class_id'=>2, 'price'=>91 ],
            ['flight_id'=>'HV.125', 'class_id'=>1, 'price'=>72 ],
            ['flight_id'=>'HV.125', 'class_id'=>2, 'price'=>82 ],
            ['flight_id'=>'HV.126', 'class_id'=>1, 'price'=>44 ],
            ['flight_id'=>'HV.126', 'class_id'=>2, 'price'=>57 ],
            ['flight_id'=>'HV.127', 'class_id'=>1, 'price'=>69 ],
            ['flight_id'=>'HV.127', 'class_id'=>2, 'price'=>88 ],
            ['flight_id'=>'HV.128', 'class_id'=>1, 'price'=>32 ],
            ['flight_id'=>'HV.128', 'class_id'=>2, 'price'=>59 ],
            ['flight_id'=>'HV.129', 'class_id'=>1, 'price'=>50 ],
            ['flight_id'=>'HV.129', 'class_id'=>2, 'price'=>67 ],
            ['flight_id'=>'HV.130', 'class_id'=>1, 'price'=>38 ],
            ['flight_id'=>'HV.130', 'class_id'=>2, 'price'=>57 ],
            ['flight_id'=>'HV.131', 'class_id'=>1, 'price'=>52 ],
            ['flight_id'=>'HV.131', 'class_id'=>2, 'price'=>65 ],
            ['flight_id'=>'HV.132', 'class_id'=>1, 'price'=>75 ],
            ['flight_id'=>'HV.132', 'class_id'=>2, 'price'=>91 ],
            ['flight_id'=>'HV.133', 'class_id'=>1, 'price'=>99 ],
            ['flight_id'=>'HV.133', 'class_id'=>2, 'price'=>111 ],
            ['flight_id'=>'HV.134', 'class_id'=>1, 'price'=>84 ],
            ['flight_id'=>'HV.134', 'class_id'=>2, 'price'=>105 ],
            ['flight_id'=>'HV.135', 'class_id'=>1, 'price'=>71 ],
            ['flight_id'=>'HV.135', 'class_id'=>2, 'price'=>96 ],
            ['flight_id'=>'HV.136', 'class_id'=>1, 'price'=>76 ],
            ['flight_id'=>'HV.136', 'class_id'=>2, 'price'=>103 ],
            ['flight_id'=>'HV.137', 'class_id'=>1, 'price'=>75 ],
            ['flight_id'=>'HV.137', 'class_id'=>2, 'price'=>101 ],
            ['flight_id'=>'HV.138', 'class_id'=>1, 'price'=>60 ],
            ['flight_id'=>'HV.138', 'class_id'=>2, 'price'=>79 ],
            ['flight_id'=>'HV.139', 'class_id'=>1, 'price'=>55 ],
            ['flight_id'=>'HV.139', 'class_id'=>2, 'price'=>76 ],
            ['flight_id'=>'HV.140', 'class_id'=>1, 'price'=>39 ],
            ['flight_id'=>'HV.140', 'class_id'=>2, 'price'=>62 ],
            ['flight_id'=>'HV.141', 'class_id'=>1, 'price'=>36 ],
            ['flight_id'=>'HV.141', 'class_id'=>2, 'price'=>47 ],
            ['flight_id'=>'HV.142', 'class_id'=>1, 'price'=>83 ],
            ['flight_id'=>'HV.142', 'class_id'=>2, 'price'=>98 ],
            ['flight_id'=>'HV.143', 'class_id'=>1, 'price'=>34 ],
            ['flight_id'=>'HV.143', 'class_id'=>2, 'price'=>54 ],
            ['flight_id'=>'HV.144', 'class_id'=>1, 'price'=>84 ],
            ['flight_id'=>'HV.144', 'class_id'=>2, 'price'=>104 ],
            ['flight_id'=>'HV.145', 'class_id'=>1, 'price'=>77 ],
            ['flight_id'=>'HV.145', 'class_id'=>2, 'price'=>97 ],
            ['flight_id'=>'HV.146', 'class_id'=>1, 'price'=>61 ],
            ['flight_id'=>'HV.146', 'class_id'=>2, 'price'=>85 ],
            ['flight_id'=>'HV.147', 'class_id'=>1, 'price'=>50 ],
            ['flight_id'=>'HV.147', 'class_id'=>2, 'price'=>78 ],
            ['flight_id'=>'HV.148', 'class_id'=>1, 'price'=>80 ],
            ['flight_id'=>'HV.148', 'class_id'=>2, 'price'=>91 ],
            ['flight_id'=>'HV.149', 'class_id'=>1, 'price'=>24 ],
            ['flight_id'=>'HV.149', 'class_id'=>2, 'price'=>49 ],
            ['flight_id'=>'HV.150', 'class_id'=>1, 'price'=>74 ],
            ['flight_id'=>'HV.150', 'class_id'=>2, 'price'=>87 ],
            ['flight_id'=>'HV.151', 'class_id'=>1, 'price'=>92 ],
            ['flight_id'=>'HV.151', 'class_id'=>2, 'price'=>116 ],
            ['flight_id'=>'HV.152', 'class_id'=>1, 'price'=>68 ],
            ['flight_id'=>'HV.152', 'class_id'=>2, 'price'=>78 ],
            ['flight_id'=>'HV.153', 'class_id'=>1, 'price'=>76 ],
            ['flight_id'=>'HV.153', 'class_id'=>2, 'price'=>101 ],
            ['flight_id'=>'HV.154', 'class_id'=>1, 'price'=>43 ],
            ['flight_id'=>'HV.154', 'class_id'=>2, 'price'=>71 ],
            ['flight_id'=>'HV.155', 'class_id'=>1, 'price'=>23 ],
            ['flight_id'=>'HV.155', 'class_id'=>2, 'price'=>40 ],
            ['flight_id'=>'HV.156', 'class_id'=>1, 'price'=>26 ],
            ['flight_id'=>'HV.156', 'class_id'=>2, 'price'=>38 ],
            ['flight_id'=>'HV.157', 'class_id'=>1, 'price'=>27 ],
            ['flight_id'=>'HV.157', 'class_id'=>2, 'price'=>47 ],
            ['flight_id'=>'HV.158', 'class_id'=>1, 'price'=>90 ],
            ['flight_id'=>'HV.158', 'class_id'=>2, 'price'=>101 ],
            ['flight_id'=>'HV.159', 'class_id'=>1, 'price'=>84 ],
            ['flight_id'=>'HV.159', 'class_id'=>2, 'price'=>110 ],
            ['flight_id'=>'HV.160', 'class_id'=>1, 'price'=>65 ],
            ['flight_id'=>'HV.160', 'class_id'=>2, 'price'=>76 ],
            ['flight_id'=>'HV.161', 'class_id'=>1, 'price'=>95 ],
            ['flight_id'=>'HV.161', 'class_id'=>2, 'price'=>108 ],
        ]);
    }
}
